### ISSUE TITLE
Nullable types don't get set

### ISSUE THREAD

**Issue by ross2411** [UnoSD/Moq.Dapper#10]
I've got complex objects which have nullable types (ie `int?`, `DateTimeOffSet?`). The Moq.Dapper extension for QueryAsync seems to set these all to null instead of their value.  I attempted a PR to fix this because I noticed you are restricting the types to non-null types.  Adding nullable types just throws an exception in Dapper though.
Any ideas?

**Comment by UnoSD** [comment]
Now it supports nullables :) 52dbe8656dfd5b76eceefcb7687c4358e08e93c1

It probably won't support DateTimeOffset as it's not a primitive, but it's a bit late in my time zone. Have a look at my last commit, it should be easy to add and I would welcome a PR to fix it.

**Comment by UnoSD** [comment]
Got carried away. It was an easy change, now it supports also non-primitive 5137d0789a9900481055fc2d1ceaa2ec7ef1ac62

**Comment by ross2411** [comment]
Thanks for the speedy response.  I've just raised a PR which adds support for the async query.  Could you take a look when you get a chance.  I've had issues with the unit test though

**Comment by UnoSD** [comment]
No problem, it may be a while as I may be away next weekend, but thank you for the contribution and I'll merge it in as soon as I can.
