### ISSUE TITLE
Lazy evaluation of .Returns() doesn't work.  .Callback() is broken.

### ISSUE THREAD

**Issue by Kintar** [UnoSD/Moq.Dapper#14]
I've added unit tests to demonstrate what I mean in a fork at [https://github.com/Kintar/Moq.Dapper](https://github.com/Kintar/Moq.Dapper).

Basically, this prevents randomized results in queries and adjusting results based on number of executions or query parameters.

I don't understand Moq well enough to fix this myself (yet), so I thought I'd open an issue so that others can look into it as I try and educate myself enough to fix it.

**Comment by UnoSD** [comment]
Thanks @Kintar for the unit test, as soon as I have some spare time I will fix it and make it work with Callback.

**Comment by UnoSD** [comment]
Hi @Kintar, just pushed new changes, it now supports both deferring and callbacks.
