### ISSUE TITLE
Suggestion - convert main unit tests to dotnet core

### ISSUE THREAD

**Issue by jhgoodwin** [UnoSD/Moq.Dapper#26]
I suggest you move the main unit tests to be dotnet core compatible and only move the DataContext code to exist outside as a Framework only and tests that rely on Framework. This will allow the main development to continue in dotnet core.

**Comment by UnoSD** [comment]
Hi @jhgoodwin, thanks for the PR, I will hopefully have time to look at it and merge it this weekend.

**Comment by UnoSD** [comment]
I think this was merged
