### ISSUE TITLE
Suggestion: Add query resolver to handle all mocks

### ISSUE THREAD

**Issue by jhgoodwin** [UnoSD/Moq.Dapper#29]
I suggest instead of coding up mock methods for every permutation of what is needed that a resolver system be added.

The idea works like this:

* Register a resolver with the mock, returning generic of T matching Query and other related methods
* Resolver accepts a query sql, parameters, then returns the resolved output.

One possible such implementation would be a resource driven resolver. Store the queries, the parameter values, then resolve those to query outputs. If no query can be resolved, the resource resolver should tell the user that the resources do not contain the query/parameter combination, and how to fix it. Then, the answer to mocking would be to put in known query results for known query inputs. In a later date, if you change the query, or inputs, the match will be broken allowing you to take action to fix it.

Thoughts?

I was looking to work on such an idea and wondered if you would be interested in adding it to your repo if I did a PR.

**Comment by UnoSD** [comment]
Hi @jhgoodwin, thanks for the suggestion. I think that's how Moq works if I get your gist (Can you write here a small code sample of how the API would look like (just an high level behaviour here, no PR or actual implementation) just to make sure I understood correctly?)

The mock would be stateful resolver like: `Query("sql1").Returns(a)` and `Query("sql2").Returns(b)` so if you invoke it with sql1 it gives you a and b if with sql2?

**Comment by jhgoodwin** [comment]
Hi UnoSD,

The idea I had was to do something like this:

Create a wrapper setup which allows you to pass in the resolver. This would be similar to your SetupDapper.

A resolver would look something like this:
```
public interface IQueryResolver
{
    IEnumerable<T> ResolveQuery<T>(string query, DynamicParameters parameters);
}
```
An example resource based one would have a lookup table of query/parameter combinations, which would point to an embedded resource of say, JSON results.

The end result would be that it would be possible to mock up your test cases by simply adding more data, never writing more mock boiler plate.

I hope this makes sense.

John

**Comment by UnoSD** [comment]
Hi John,

thanks for the explanation. So the benefit would be to rely on an external data source (IQueryResolver) instead of mocking each call which may be verbose when mocked data gets big (as for small data sets would just be more verbose).

Do you find many scenarios where you need to mock a lot of dynamic data?

Conceptually sounds good; but where would you store the resolver? Pardon my laziness for not checking, but do the `Mock`s have auxiliary storage? Would we need to keep a static dictionary of mock->resolver globally?

Thanks.
Stef

**Comment by jhgoodwin** [comment]
Hi Stef,

So in my case, I am working with a system that has a lot of scientific data. Mocking it up is kind of painful. Rather than mock the data, I'd rather just take the real data as an example, then find new examples which prove any new cases.

Right now, we're redeveloping an older app, so we may have a lot of small queries to write. Being a naturally born lazy man, I don't really want to mock up every getter function for my tests, but I do want them tested (so they don't come back to me as broken out of the gate).

As far as where the resolver would be stored, I'd probably create an instance of it and the setup with the test class setup just like I do when I do the Moq.Dapper setup calls.

Regarding the test data storage, preliminarily, I was planning to use embedded resources so that I don't have to worry about the data not being available during the test or in the wrong path.  With .NET Core, adding a pile of json files in a folder as embedded resources is a single command in the csproj file.

I will have some mandatory PTO in about 3 weeks, so if I don't make time before then, I'll work on some designs for it so you can see more discretely.

In the end you'd have:
* Test class setup one liner to hook up the resolver
* Resource files with the query data
* Resource index file with the query / parameter value combinations
* Ideal resolver implementation should throw for any unmocked data when you hit that code.
* When unmocked sql is hit, you just run it 1x in real life, copy the data to the resources folder, then bash on the test.

Hope this makes sense,

John

**Comment by UnoSD** [comment]
Hi John,

thanks for the explanation, I'll be happy to have a look at the PR. I will have some time off at the beginning of December (I know, not really close) and I can definitely work more actively on it then.

Thanks.
Stef

**Comment by jhgoodwin** [comment]
I was thinking about this a lot over my winter break. In addition, I read a lot of Dapper and Moq.Dapper code. After all that, I'm coming to the conclusion that my suggestion is more accurately a generic wrapper for IDbCommand and related classes to allow trivial implementation of a persistent cache. I'm going to do some playing around, but the short of this conclusion is that I don't think I'll have to change this project to implement my idea. Thanks for talking through this idea with me.

**Comment by UnoSD** [comment]
More than happy to discuss also this idea with you; apologies if I have not touched this repository in a while, but I ended up more busy during my time off than when I was actually working. I will try my best to have a look at PR as soon as I can (I know you also have had another one pending for a while, sorry for that).
