### ISSUE TITLE
Version for .NET Core/Standard

### ISSUE THREAD

**Issue by activebiz** [UnoSD/Moq.Dapper#3]
Great library, exactly what I was looking for. 

However its only available for full .NET. Is there a plan in place to make it available for .NET core or .NET standard ?

**Comment by UnoSD** [comment]
Thanks. I initially created a .NET Standard library but I had some issue with code analysis and IntelliSense so I switched back to the full framework. If VS will get patched properly I reckon it will be pretty easy to migrate back. Will keep this open but unfortunately it might take a while as I don't have much time to work on it now, happy to approve PRs to change it.

**Comment by UnoSD** [comment]
Quick update, I wanted to migrate to .NET Standard, but apparently my Visual Studio doesn't let me debug variables when I use .NET Standard, I'm in touch with Microsoft and hopefully I will be able to migrate soon.

**Comment by mcattle** [comment]
With Visual Studio 2017.3 adding lots of .NET Standard love alongside .NET Core 2.0, and 2017.4 now out, does this unblock the migration?

I, too, would love to see this as a .NET Standard library.

**Comment by UnoSD** [comment]
@mcattle I updated to 15.4 now and I still can't debug .NET Core/.NET Standard libs... Tried to get in touch with Microsoft, but getting a support ticket through is a nightmare. I will likely re-image my machine later and then it will probably work.

If I have some spare time this weekend, I may try develop it in Rider, if that goes well, I will migrate to .NET Std.

**Comment by UnoSD** [comment]
Now Moq.Dapper is a .NET Standard project and package from 62fdd1cd68d27a0ad5d5d8ce12e7fb5fbb569941

Moq.DataContext cannot be migrated as it uses Remoting and RealProxy which are unsupported APIs for .NET Standard.
