### ISSUE TITLE
SetupDapperAsync() on Dapper ExecuteAsync() method throws NotSupportedException

### ISSUE THREAD

**Issue by davemcmanus** [UnoSD/Moq.Dapper#31]
The following code causes a SystemNotSupportedException:
```
var mockDbConn = new Mock<IDbConnection>();
mockDbConn.SetupDapperAsync(x => x.ExecuteAsync(It.IsAny<string>(), 
    It.IsAny<object>(),
    It.IsAny<IDbTransaction>(),
    It.IsAny<int?>(),
    It.IsAny<CommandType?>())
).ReturnsAsync(1);
```

Not sure what is causing the issue. Any suggestions?

**Comment by davemcmanus** [comment]
I figured out the issue. I was using "IDbConnection" instead of "DbConnection". Perhaps the source should be updated to not throw exceptions on IDbConnection.

**Comment by UnoSD** [comment]
Hi @davemcmanus, the `IDbConnection` interface exposes `IDbCommand` which itself has no async methods at all (see https://docs.microsoft.com/en-us/dotnet/api/system.data.idbcommand?view=netframework-4.7.2 and https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbcommand?view=netframework-4.7.2).

The async versions are only present on the `DbCommand` class exposed by the `DbConnection`. Even when you use `IDbConnection` Dapper internally downcast it to a DbConnection therefore it would give you an exception anyway on that side.

**Comment by davemcmanus** [comment]
> Hi @davemcmanus, the `IDbConnection` interface exposes `IDbCommand` which itself has no async methods at all (see https://docs.microsoft.com/en-us/dotnet/api/system.data.idbcommand?view=netframework-4.7.2 and https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbcommand?view=netframework-4.7.2).
> 
> The async versions are only present on the `DbCommand` class exposed by the `DbConnection`. Even when you use `IDbConnection` Dapper internally downcast it to a DbConnection therefore it would give you an exception anyway on that side.

@UnoSD Thanks for your reply. Makes sense.
