### ISSUE TITLE
Query on Complex Types that have Enums - don't work

### ISSUE THREAD

**Issue by jason-e-gross** [UnoSD/Moq.Dapper#35]
If my complex type has an enum in it - that will normally map to an INT/ENUM pairing in the database to POCO query -- this returns always a zero.

```
			var expected = new[] {
				new FancyObject{Desired="2", DeviceGUID = Guid.Parse(validGUID),  Installed="1", ImageTypeID = ImageType.BODY_IMAGE},
				new FancyObject{Desired="4", DeviceGUID = Guid.Parse(validGUID),  Installed="3", ImageTypeID = ImageType.HEADER_IMAGE}
			};
			connection.SetupDapper(c => c.Query<FancyObject>(It.IsAny<string>(), null, null, true, null, null)).Returns(expected);

// using this, the "expected" object is returned, but the ENUM (ImageTypeID) is 0
```
Using that object above as a Returns -- the ImageTypeID (an enum in FancyObject, but an INT in DB -- returns 0 - always).

All the other fields return the right values -- just the ENUM conversion seems to fail - it's 0 when returning the expected.

**Comment by mcalvinsf** [comment]
I see the same thing you described @jason-e-gross.  Did you ever find a solution ?

**Comment by ViniCorrea** [comment]
I'm having the same issue. Does someone know some workaround?
