### ISSUE TITLE
ArgumentNullException when i pass an array as a parameter

### ISSUE THREAD

**Issue by lucasteles** [UnoSD/Moq.Dapper#36]
I got an argument null error when i tried to use an array as an sql parameter

```cs
var ids = new[] {1, 2, 3};
var result = connection.Query<Model>("SELECT * FROM TABLE WHERE id in @IDS", new {  IDS =  ids });
```
Debuging dapper i found that  `command.CommandText' is null on SqlMapper class, what is causing this
![image](https://user-images.githubusercontent.com/3037609/52448527-5d3e8300-2b1b-11e9-8a52-4c8122078f31.png)

**Comment by hienkhieu** [comment]
Same here.
