### ISSUE TITLE
vs2017 nuget Install failed.

### ISSUE THREAD

**Issue by ajdre2015** [UnoSD/Moq.Dapper#50]
Attempting to gather dependency information for package 'Moq.Dapper.1.0.3' with respect to project 'serviceTests', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 1.29 sec
Attempting to resolve dependencies for package 'Moq.Dapper.1.0.3' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Moq.Dapper.1.0.3'
Resolved actions to install package 'Moq.Dapper.1.0.3'
Retrieving package 'Moq.Dapper 1.0.3' from 'nuget.org'.
Install failed. Rolling back...
Package 'Moq.Dapper.1.0.3' does not exist in project 'serviceTests'
Package 'Moq.Dapper.1.0.3' does not exist in folder 'F:\Temp\testmywcfs1\packages'
Executing nuget actions took 466.93 ms
Install-Package : Could not install package 'Moq.Dapper 1.0.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, co
ntact the package author.
At line:1 char:1
+ Install-Package Moq.Dapper -Version 1.0.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:02.2250492

**Comment by UnoSD** [comment]
Please reopen if this is still applicable, I've updated the library and packages.
