### ISSUE TITLE
Mocking SqlMapper.QueryFirstOrDefaultAsync, SqlMapper.QueryFirstAsync, and SqlMapper.QueryFirst calls are not supported

### ISSUE THREAD

**Issue by ssiltanen** [UnoSD/Moq.Dapper#54]
Error message when trying to setup dapper for QueryFirstAsync or QueryFirstOrDefaultAsync. 

Error Message:
   System.NotSupportedException : Specified method is not supported.
  Stack Trace:
     at Moq.Dapper.DbConnectionInterfaceMockExtensions.SetupDapper[TResult](Mock`1 mock, Expression`1 expression)

**Comment by ksadralodabaisti** [comment]
> Error message when trying to setup dapper for QueryFirstAsync or QueryFirstOrDefaultAsync.
> 
> Error Message:
> System.NotSupportedException : Specified method is not supported.
> Stack Trace:
> at Moq.Dapper.DbConnectionInterfaceMockExtensions.SetupDapper[TResult](Mock`1 mock, Expression`1 expression)

Any follow up on this? I am hitting the same problem with ExecuteReaderAsync. Get and Query (not First) also work.

**Comment by joshuaquiz** [comment]
https://github.com/UnoSD/Moq.Dapper/issues/58 from another thread

**Comment by imad-mn** [comment]
Any follow up on this ??? I have same problem with `QueryFirstOrDefaultAsync()` and `ExecuteAsync()`

**Comment by UnoSD** [comment]
https://github.com/UnoSD/Moq.Dapper/pull/53/files

merged

**Comment by kokosky93** [comment]
@UnoSD generic QueryFirstAsync doesn't work for string type.
QueryFirstAsync<string> -> exception => sequence contains no elements
QueryFirstAsync<int> -> it works

Can you check please
