### ISSUE TITLE
License forbids linking with proprietary code

### ISSUE THREAD

**Issue by czers** [UnoSD/Moq.Dapper#6]
It seems that this library is published under GPL-2.0 license which forbids linking with proprietary (non-GPL compatible) code. Is this intentional?

I would like to use this library in my work, but I wouldn't want to get into any legal problems because of that.

**Comment by UnoSD** [comment]
I picked the GPL-2.0 as I knew it was more permissive than GPL-3.0, I am happy for you to use it in proprietary applications without sharing your source code anyway, I would just like my library to be mentioned if it's distributed with your software. I will consider changing license, but I am quite busy to look into this.

That said, the library is for unit testing, do you distribute your application with the testing libraries? If it's not used in the distributed application I think there is no legal problem.

**Comment by UnoSD** [comment]
Haven't heard anything in a while about this issue, I am going to close it.
