### ISSUE TITLE
Doesn't support the latest version of Moq

### ISSUE THREAD

**Issue by JoeySelahJr** [UnoSD/Moq.Dapper#62]
I get this error when I try to use Moq.Dapper with the latest version of Moq.

`Assembly 'Moq.Dapper' with identity 'Moq.Dapper, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null' uses 'Moq, Version=4.12.0.0, Culture=neutral, PublicKeyToken=69f491c39445e920' which has a higher version than referenced assembly 'Moq' with identity 'Moq, Version=4.7.0.0, Culture=neutral, PublicKeyToken=69f491c39445e920'
`

**Comment by hopedrivendeveloper** [comment]
@JoeySelahJr I think it's vice versa, your installed version of Moq is 4.7.0.0, but `Moq.Dapper` requires 4.12.0.0

**Comment by UnoSD** [comment]
I've upgraded all the libraries and seems to work well.
