### ISSUE TITLE
License GPLv2 to MIT, BSD or Apache2

### ISSUE THREAD

**Issue by fabrizziocht** [UnoSD/Moq.Dapper#65]
Hello, Is it posible to modify the license to MIT, BSD or Apache2?, Moq is under BSDv3 and it's posible to use it with commercial private software, but it's incompatible to use this library in this scenarios.

**Comment by UnoSD** [comment]
Being a test library, you should be free to use it for commercial private software, unless you are trying to ship the library in production which would not make so much sense being for test.
