### ISSUE TITLE
Could not install using .Net 4.5 or above

### ISSUE THREAD

**Issue by rodo593** [UnoSD/Moq.Dapper#8]
Sorry, my bad, it's only available for Net Standard 2.0.

> I'm trying to install the latest version (1.0.0.4) using .Net 4.5 from Nuget, but I can't.
> This is the error from Visual Studio Output.
> 
> **Error |   | Could not install package 'Moq.Dapper 1.0.0.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.**
> 
> Thanks!

**Comment by UnoSD** [comment]
No worries, I'm going to close this. I may, at some point, try to lower the .NET Standard version as the library may not need the new APIs.

**Comment by Almenon** [comment]
I got the same problem with .net 4.6.2 :(

It thought it was compatible with .net core v2 but apparently you need the core sdk installed (comes with VS2017) if you want to use a core v2 nuget package with .net 4.6.2
